# Generated by Django 4.0.4 on 2022-05-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_footeraboutus_alter_startinfo_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterAboutUs',
            new_name='FooterAbout',
        ),
    ]
