# Generated by Django 4.0.4 on 2022-05-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_footeraboutus_footerabout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerabout',
            old_name='content',
            new_name='infotext',
        ),
    ]
