# Generated by Django 4.0.4 on 2022-05-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_content_footerabout_infotext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterAbout',
        ),
    ]
