# Generated by Django 4.0.4 on 2022-05-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_startpage_about_img_startpage_contact_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startpage',
            name='about_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='startpage',
            name='contact_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='startpage',
            name='services_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
