# Generated by Django 4.0.4 on 2022-05-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_startpage_about_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topcontent', models.TextField()),
                ('box1Title', models.CharField(max_length=200)),
                ('box2Title', models.CharField(max_length=200)),
                ('box1Des', models.TextField()),
                ('box2Des', models.TextField()),
                ('box1_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('box2_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
