# Generated by Django 4.0.4 on 2022-05-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='box1Des',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='box1Title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='box1_img',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='box2Des',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='box2Title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='box2_img',
        ),
    ]
