# Generated by Django 4.0.4 on 2022-05-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_aboutpage_box1des_remove_aboutpage_box1title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='box1Des',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='box1Title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='box1_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
