# Generated by Django 4.0.4 on 2022-05-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_aboutpage_box2des_aboutpage_box2title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('listitem', models.CharField(max_length=200, null=True)),
                ('topcontent', models.TextField()),
                ('box1Title', models.CharField(max_length=200, null=True)),
                ('box2Title', models.CharField(max_length=200, null=True)),
                ('box1_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('box2_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('box2Des', models.TextField(null=True)),
            ],
        ),
    ]
