# Generated by Django 4.0.4 on 2022-05-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_servicelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelist',
            name='listitem',
        ),
        migrations.AddField(
            model_name='servicelist',
            name='box1Des',
            field=models.TextField(null=True),
        ),
    ]
