# Generated by Django 4.0.4 on 2022-05-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_servicelist_listitem_servicelist_box1des'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceList',
            new_name='Services',
        ),
    ]
