# Generated by Django 4.0.4 on 2022-05-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='AboutPage',
            new_name='AboutModel',
        ),
        migrations.RenameModel(
            old_name='Estimate',
            new_name='EstimateModel',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='ServiceModel',
        ),
        migrations.RenameModel(
            old_name='StartPage',
            new_name='StartModel',
        ),
    ]
