# Generated by Django 4.0.4 on 2022-05-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_referencemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='box1_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='box2_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='box1_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='box2_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
        migrations.AlterField(
            model_name='startmodel',
            name='contact_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
        migrations.AlterField(
            model_name='startmodel',
            name='services_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
    ]
