# Generated by Django 4.0.4 on 2022-06-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_aboutmodel_box1_img_alter_aboutmodel_box2_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startmodel',
            name='start_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
        migrations.AlterField(
            model_name='startmodel',
            name='about_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
    ]
