# Generated by Django 4.0.4 on 2022-06-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_startmodel_start_img_alter_startmodel_about_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startmodel',
            name='title',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
    ]
