# Generated by Django 4.0.4 on 2022-06-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_startmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencemodel',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='referencemodel',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='referencemodel',
            name='caption',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
