# Generated by Django 4.0.4 on 2022-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_referencemodel_content_referencemodel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%y'),
        ),
    ]
