# Generated by Django 4.0.4 on 2022-06-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_referencemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencemodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='referencemodel',
            name='title',
        ),
    ]
